# Generated by Django 5.2.17 on 2026-08-16 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("parlamentares", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusTramitacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Descrição"
                    ),
                ),
                (
                    "fim_tramitacao",
                    models.BooleanField(
                        default=False, verbose_name="Encerra a tramitação?"
                    ),
                ),
            ],
            options={
                "verbose_name": "Status de Tramitação",
                "verbose_name_plural": "Status de Tramitação",
                "ordering": ("descricao",),
            },
        ),
        migrations.CreateModel(
            name="TipoMateria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sigla",
                    models.CharField(max_length=10, unique=True, verbose_name="Sigla"),
                ),
                (
                    "descricao",
                    models.CharField(max_length=100, verbose_name="Descrição"),
                ),
                (
                    "exige_analise_previa",
                    models.BooleanField(
                        default=False,
                        help_text="APLs passam pela Análise Prévia da Procuradoria antes de se converterem em projeto.",
                        verbose_name="Exige Análise Prévia?",
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=100, verbose_name="Ordem de exibição"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Matéria",
                "verbose_name_plural": "Tipos de Matéria",
                "ordering": ("ordem", "sigla"),
            },
        ),
        migrations.CreateModel(
            name="UnidadeTramitacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=150, unique=True, verbose_name="Nome"),
                ),
                ("ativa", models.BooleanField(default=True, verbose_name="Ativa")),
            ],
            options={
                "verbose_name": "Unidade de Tramitação",
                "verbose_name_plural": "Unidades de Tramitação",
                "ordering": ("nome",),
            },
        ),
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("V", "Vereador"),
                            ("M", "Mesa Diretora"),
                            ("C", "Comissão"),
                            ("P", "Poder Executivo"),
                            ("I", "Iniciativa Popular"),
                        ],
                        max_length=1,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True,
                        help_text="Preenchido automaticamente para vereador/comissão.",
                        max_length=200,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "comissao",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="autor",
                        to="parlamentares.comissao",
                        verbose_name="Comissão",
                    ),
                ),
                (
                    "vereador",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="autor",
                        to="parlamentares.vereador",
                        verbose_name="Vereador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Autor",
                "verbose_name_plural": "Autores",
                "ordering": ("nome",),
            },
        ),
        migrations.CreateModel(
            name="Autoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "principal",
                    models.BooleanField(
                        default=True,
                        help_text="Art. 88, §2º: considera-se autor o primeiro signatário. Coautoria admitida (§3º).",
                        verbose_name="Primeiro signatário?",
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="materias.autor",
                        verbose_name="Autor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Autoria",
                "verbose_name_plural": "Autorias",
            },
        ),
        migrations.CreateModel(
            name="Materia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField(verbose_name="Número")),
                ("ano", models.PositiveIntegerField(verbose_name="Ano")),
                (
                    "processo_numero",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Processo administrativo (Processo nº XXXX/AAAA).",
                        null=True,
                        verbose_name="Nº do Processo",
                    ),
                ),
                (
                    "processo_ano",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ano do Processo"
                    ),
                ),
                ("ementa", models.TextField(verbose_name="Ementa")),
                (
                    "data_apresentacao",
                    models.DateField(verbose_name="Data de Apresentação"),
                ),
                (
                    "regime",
                    models.CharField(
                        choices=[
                            ("U", "Urgência"),
                            ("E", "Tramitação Especial"),
                            ("P", "Prioridade"),
                            ("O", "Tramitação Ordinária"),
                        ],
                        default="O",
                        max_length=1,
                        verbose_name="Regime de Tramitação",
                    ),
                ),
                (
                    "em_tramitacao",
                    models.BooleanField(default=True, verbose_name="Em tramitação?"),
                ),
                (
                    "texto",
                    models.FileField(
                        blank=True,
                        upload_to="materias/%Y/",
                        verbose_name="Texto integral",
                    ),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="Observação")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "apensada_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="apensadas",
                        to="materias.materia",
                        verbose_name="Apensada à matéria",
                    ),
                ),
                (
                    "autores",
                    models.ManyToManyField(
                        related_name="materias",
                        through="materias.Autoria",
                        to="materias.autor",
                        verbose_name="Autores",
                    ),
                ),
                (
                    "materia_origem",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ex.: o APL que deu origem a este Projeto de Lei.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materias_derivadas",
                        to="materias.materia",
                        verbose_name="Matéria de origem",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materias",
                        to="materias.tipomateria",
                        verbose_name="Tipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matéria Legislativa",
                "verbose_name_plural": "Matérias Legislativas",
                "ordering": ("-ano", "-numero"),
            },
        ),
        migrations.CreateModel(
            name="DocumentoAcessorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                ("data", models.DateField(blank=True, null=True, verbose_name="Data")),
                (
                    "arquivo",
                    models.FileField(
                        blank=True, upload_to="documentos/%Y/", verbose_name="Arquivo"
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="materias.materia",
                        verbose_name="Matéria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Acessório",
                "verbose_name_plural": "Documentos Acessórios",
                "ordering": ("-data", "-id"),
            },
        ),
        migrations.AddField(
            model_name="autoria",
            name="materia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="materias.materia"
            ),
        ),
        migrations.CreateModel(
            name="AnalisePrevia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data da análise")),
                (
                    "admissibilidade_art88",
                    models.CharField(
                        choices=[
                            ("OK", "Sem óbice"),
                            ("RE", "Com ressalvas"),
                            ("VI", "Com vício/óbice"),
                            ("NA", "Não se aplica"),
                        ],
                        default="OK",
                        max_length=2,
                        verbose_name="Admissibilidade (art. 88, RI)",
                    ),
                ),
                (
                    "prejudicialidade_art142",
                    models.CharField(
                        choices=[
                            ("OK", "Sem óbice"),
                            ("RE", "Com ressalvas"),
                            ("VI", "Com vício/óbice"),
                            ("NA", "Não se aplica"),
                        ],
                        default="OK",
                        max_length=2,
                        verbose_name="Prejudicialidade (art. 142, RI)",
                    ),
                ),
                (
                    "constitucionalidade_material",
                    models.CharField(
                        choices=[
                            ("OK", "Sem óbice"),
                            ("RE", "Com ressalvas"),
                            ("VI", "Com vício/óbice"),
                            ("NA", "Não se aplica"),
                        ],
                        default="OK",
                        max_length=2,
                        verbose_name="Constitucionalidade material",
                    ),
                ),
                (
                    "constitucionalidade_formal_objetiva",
                    models.CharField(
                        choices=[
                            ("OK", "Sem óbice"),
                            ("RE", "Com ressalvas"),
                            ("VI", "Com vício/óbice"),
                            ("NA", "Não se aplica"),
                        ],
                        default="OK",
                        max_length=2,
                        verbose_name="Constitucionalidade formal objetiva (processo legislativo)",
                    ),
                ),
                (
                    "constitucionalidade_formal_subjetiva",
                    models.CharField(
                        choices=[
                            ("OK", "Sem óbice"),
                            ("RE", "Com ressalvas"),
                            ("VI", "Com vício/óbice"),
                            ("NA", "Não se aplica"),
                        ],
                        default="OK",
                        max_length=2,
                        verbose_name="Constitucionalidade formal subjetiva (iniciativa)",
                    ),
                ),
                (
                    "tecnica_legislativa",
                    models.CharField(
                        choices=[
                            ("OK", "Sem óbice"),
                            ("RE", "Com ressalvas"),
                            ("VI", "Com vício/óbice"),
                            ("NA", "Não se aplica"),
                        ],
                        default="OK",
                        max_length=2,
                        verbose_name="Técnica legislativa (art. 92, RI)",
                    ),
                ),
                (
                    "fundamentacao",
                    models.TextField(
                        blank=True,
                        help_text="Análise desenvolvida item a item.",
                        verbose_name="Fundamentação",
                    ),
                ),
                (
                    "conclusao",
                    models.CharField(
                        choices=[
                            ("A", "Admissível — apto a tramitar"),
                            ("R", "Admissível com ressalvas"),
                            ("I", "Inadmissível (art. 88, RI)"),
                            ("P", "Prejudicada (art. 142, RI)"),
                        ],
                        max_length=1,
                        verbose_name="Conclusão",
                    ),
                ),
                (
                    "responsavel",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="Responsável pela análise",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        blank=True,
                        upload_to="analises/%Y/",
                        verbose_name="Arquivo da Análise",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analises_previas",
                        to="materias.materia",
                        verbose_name="Matéria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Análise Prévia",
                "verbose_name_plural": "Análises Prévias",
                "ordering": ("-data", "-id"),
            },
        ),
        migrations.CreateModel(
            name="Parecer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sentido",
                    models.CharField(
                        choices=[
                            ("F", "Favorável"),
                            ("C", "Contrário"),
                            ("E", "Favorável com emendas"),
                        ],
                        max_length=1,
                        verbose_name="Sentido",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "texto",
                    models.TextField(
                        blank=True, verbose_name="Texto/ementa do parecer"
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        blank=True, upload_to="pareceres/%Y/", verbose_name="Arquivo"
                    ),
                ),
                (
                    "comissao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pareceres",
                        to="parlamentares.comissao",
                        verbose_name="Comissão",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pareceres",
                        to="materias.materia",
                        verbose_name="Matéria",
                    ),
                ),
                (
                    "relator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relatorias",
                        to="parlamentares.vereador",
                        verbose_name="Relator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parecer de Comissão",
                "verbose_name_plural": "Pareceres de Comissões",
                "ordering": ("-data",),
            },
        ),
        migrations.CreateModel(
            name="Tramitacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "despacho",
                    models.TextField(blank=True, verbose_name="Texto do despacho"),
                ),
                (
                    "data_prazo",
                    models.DateField(
                        blank=True,
                        help_text="Art. 54, RI: 3 dias (urgência), 9 (prioridade), 15 (ordinária) para parecer de comissão.",
                        null=True,
                        verbose_name="Prazo regimental",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tramitacoes",
                        to="materias.materia",
                        verbose_name="Matéria",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="materias.statustramitacao",
                        verbose_name="Status",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
                (
                    "unidade_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tramitacoes_destino",
                        to="materias.unidadetramitacao",
                        verbose_name="Unidade de destino",
                    ),
                ),
                (
                    "unidade_origem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tramitacoes_origem",
                        to="materias.unidadetramitacao",
                        verbose_name="Unidade de origem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tramitação",
                "verbose_name_plural": "Tramitações",
                "ordering": ("-data", "-id"),
            },
        ),
        migrations.AddConstraint(
            model_name="autoria",
            constraint=models.UniqueConstraint(
                fields=("materia", "autor"), name="autoria_unica"
            ),
        ),
        migrations.AddConstraint(
            model_name="materia",
            constraint=models.UniqueConstraint(
                fields=("tipo", "numero", "ano"), name="materia_unica"
            ),
        ),
    ]
