# Generated by Django 5.2.17 on 2026-08-16 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CasaLegislativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        default="Câmara Municipal de Duque de Caxias",
                        max_length=200,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "sigla",
                    models.CharField(
                        default="CMDC", max_length=20, verbose_name="Sigla"
                    ),
                ),
                (
                    "municipio",
                    models.CharField(
                        default="Duque de Caxias",
                        max_length=100,
                        verbose_name="Município",
                    ),
                ),
                ("uf", models.CharField(default="RJ", max_length=2, verbose_name="UF")),
                (
                    "endereco",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Endereço"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Telefone"
                    ),
                ),
                ("site", models.URLField(blank=True, verbose_name="Site")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "brasao",
                    models.FileField(
                        blank=True, upload_to="casa/", verbose_name="Brasão"
                    ),
                ),
            ],
            options={
                "verbose_name": "Casa Legislativa",
                "verbose_name_plural": "Casa Legislativa",
            },
        ),
        migrations.CreateModel(
            name="Legislatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(unique=True, verbose_name="Número"),
                ),
                ("data_inicio", models.DateField(verbose_name="Início")),
                ("data_fim", models.DateField(verbose_name="Fim")),
            ],
            options={
                "verbose_name": "Legislatura",
                "verbose_name_plural": "Legislaturas",
                "ordering": ("-numero",),
            },
        ),
        migrations.CreateModel(
            name="SessaoLegislativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField(verbose_name="Número")),
                ("ano", models.PositiveIntegerField(verbose_name="Ano")),
                ("data_inicio", models.DateField(verbose_name="Início")),
                ("data_fim", models.DateField(verbose_name="Fim")),
                (
                    "legislatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessoes_legislativas",
                        to="core.legislatura",
                        verbose_name="Legislatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sessão Legislativa",
                "verbose_name_plural": "Sessões Legislativas",
                "ordering": ("-ano",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("legislatura", "numero"), name="sessaolegislativa_unica"
                    )
                ],
            },
        ),
    ]
