# Generated by Django 5.2.17 on 2026-08-16 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("materias", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoNorma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sigla",
                    models.CharField(max_length=10, unique=True, verbose_name="Sigla"),
                ),
                (
                    "descricao",
                    models.CharField(max_length=100, verbose_name="Descrição"),
                ),
            ],
            options={
                "verbose_name": "Tipo de Norma",
                "verbose_name_plural": "Tipos de Norma",
                "ordering": ("sigla",),
            },
        ),
        migrations.CreateModel(
            name="Norma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=20, verbose_name="Número")),
                ("ano", models.PositiveIntegerField(verbose_name="Ano")),
                ("ementa", models.TextField(verbose_name="Ementa")),
                (
                    "data_promulgacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de promulgação"
                    ),
                ),
                (
                    "data_publicacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de publicação"
                    ),
                ),
                (
                    "veiculo_publicacao",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: Boletim Oficial do Município.",
                        max_length=100,
                        verbose_name="Veículo de publicação",
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("V", "Vigente"),
                            ("A", "Vigente com alterações"),
                            ("R", "Revogada"),
                            ("S", "Eficácia suspensa"),
                        ],
                        default="V",
                        max_length=1,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "texto",
                    models.FileField(
                        blank=True,
                        upload_to="normas/%Y/",
                        verbose_name="Texto integral",
                    ),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="Observação")),
                (
                    "materia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="normas",
                        to="materias.materia",
                        verbose_name="Matéria de origem",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="normas",
                        to="normas.tiponorma",
                        verbose_name="Tipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Norma Jurídica",
                "verbose_name_plural": "Normas Jurídicas",
                "ordering": ("-ano", "-id"),
            },
        ),
        migrations.CreateModel(
            name="VinculoNorma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("A", "Altera"),
                            ("R", "Revoga"),
                            ("P", "Revoga parcialmente"),
                            ("G", "Regulamenta"),
                            ("S", "Suspende a execução"),
                        ],
                        max_length=1,
                        verbose_name="Tipo de vínculo",
                    ),
                ),
                (
                    "observacao",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Observação"
                    ),
                ),
                (
                    "norma_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculos_passivos",
                        to="normas.norma",
                        verbose_name="Norma atingida",
                    ),
                ),
                (
                    "norma_origem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculos_ativos",
                        to="normas.norma",
                        verbose_name="Norma que age",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vínculo entre Normas",
                "verbose_name_plural": "Vínculos entre Normas",
            },
        ),
        migrations.AddConstraint(
            model_name="norma",
            constraint=models.UniqueConstraint(
                fields=("tipo", "numero", "ano"), name="norma_unica"
            ),
        ),
        migrations.AddConstraint(
            model_name="vinculonorma",
            constraint=models.UniqueConstraint(
                fields=("norma_origem", "norma_destino", "tipo"), name="vinculo_unico"
            ),
        ),
    ]
