# Generated by Django 5.2.17 on 2026-08-16 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("materias", "0001_initial"),
        ("parlamentares", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessaoPlenaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("P", "Preparatória"),
                            ("O", "Ordinária"),
                            ("E", "Extraordinária"),
                            ("S", "Solene"),
                        ],
                        default="O",
                        max_length=1,
                        verbose_name="Tipo",
                    ),
                ),
                ("numero", models.PositiveIntegerField(verbose_name="Número")),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "hora_inicio",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de início"
                    ),
                ),
                (
                    "hora_fim",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de encerramento"
                    ),
                ),
                (
                    "ata_arquivo",
                    models.FileField(
                        blank=True,
                        help_text="Versão final revisada pelo Setor de Atas.",
                        upload_to="atas/%Y/",
                        verbose_name="Ata da sessão",
                    ),
                ),
                (
                    "resumo",
                    models.TextField(blank=True, verbose_name="Resumo/observações"),
                ),
                (
                    "sessao_legislativa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessoes_plenarias",
                        to="core.sessaolegislativa",
                        verbose_name="Sessão Legislativa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sessão Plenária",
                "verbose_name_plural": "Sessões Plenárias",
                "ordering": ("-data", "-numero"),
            },
        ),
        migrations.CreateModel(
            name="PresencaSessao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "presente",
                    models.BooleanField(default=True, verbose_name="Presente?"),
                ),
                (
                    "justificativa",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Justificativa de ausência",
                    ),
                ),
                (
                    "vereador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="presencas",
                        to="parlamentares.vereador",
                        verbose_name="Vereador",
                    ),
                ),
                (
                    "sessao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presencas",
                        to="sessoes.sessaoplenaria",
                        verbose_name="Sessão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presença",
                "verbose_name_plural": "Presenças",
            },
        ),
        migrations.CreateModel(
            name="ItemPauta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fase",
                    models.CharField(
                        choices=[
                            ("EI", "Expediente Inicial"),
                            ("OD", "Ordem do Dia"),
                            ("EF", "Expediente Final"),
                        ],
                        default="OD",
                        max_length=2,
                        verbose_name="Fase",
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Ordem na pauta"
                    ),
                ),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("U", "Turno único"),
                            ("1", "Primeiro turno"),
                            ("2", "Segundo turno"),
                            ("R", "Redação Final"),
                        ],
                        default="U",
                        max_length=1,
                        verbose_name="Turno",
                    ),
                ),
                (
                    "observacao",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Observação"
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_pauta",
                        to="materias.materia",
                        verbose_name="Matéria",
                    ),
                ),
                (
                    "sessao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pauta",
                        to="sessoes.sessaoplenaria",
                        verbose_name="Sessão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Pauta",
                "verbose_name_plural": "Itens de Pauta",
                "ordering": ("sessao", "fase", "ordem"),
            },
        ),
        migrations.CreateModel(
            name="Votacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processo",
                    models.CharField(
                        choices=[
                            ("S", "Simbólica"),
                            ("N", "Nominal"),
                            ("E", "Escrutínio secreto"),
                            ("L", "Leitura (sem votação)"),
                        ],
                        default="S",
                        max_length=1,
                        verbose_name="Processo de votação",
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("A", "Aprovada"),
                            ("R", "Rejeitada"),
                            ("T", "Retirada de pauta"),
                            ("D", "Adiada"),
                            ("V", "Pedido de vista"),
                            ("P", "Prejudicada (art. 142, RI)"),
                            ("L", "Lida"),
                        ],
                        max_length=1,
                        verbose_name="Resultado",
                    ),
                ),
                (
                    "votos_sim",
                    models.PositiveIntegerField(default=0, verbose_name="Votos SIM"),
                ),
                (
                    "votos_nao",
                    models.PositiveIntegerField(default=0, verbose_name="Votos NÃO"),
                ),
                (
                    "abstencoes",
                    models.PositiveIntegerField(default=0, verbose_name="Abstenções"),
                ),
                (
                    "unanime",
                    models.BooleanField(default=False, verbose_name="Unânime?"),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="Observação")),
                (
                    "item_pauta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votacao",
                        to="sessoes.itempauta",
                        verbose_name="Item de pauta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Votação",
                "verbose_name_plural": "Votações",
            },
        ),
        migrations.CreateModel(
            name="VotoVereador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voto",
                    models.CharField(
                        choices=[
                            ("S", "Sim"),
                            ("N", "Não"),
                            ("A", "Abstenção"),
                            ("U", "Ausente"),
                            ("P", "Presidente (não vota)"),
                        ],
                        max_length=1,
                        verbose_name="Voto",
                    ),
                ),
                (
                    "vereador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="votos",
                        to="parlamentares.vereador",
                        verbose_name="Vereador",
                    ),
                ),
                (
                    "votacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votos",
                        to="sessoes.votacao",
                        verbose_name="Votação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voto de Vereador",
                "verbose_name_plural": "Votos de Vereadores",
            },
        ),
        migrations.AddConstraint(
            model_name="sessaoplenaria",
            constraint=models.UniqueConstraint(
                fields=("tipo", "numero", "sessao_legislativa"), name="sessao_unica"
            ),
        ),
        migrations.AddConstraint(
            model_name="presencasessao",
            constraint=models.UniqueConstraint(
                fields=("sessao", "vereador"), name="presenca_unica"
            ),
        ),
        migrations.AddConstraint(
            model_name="votovereador",
            constraint=models.UniqueConstraint(
                fields=("votacao", "vereador"), name="voto_unico"
            ),
        ),
    ]
