# Generated by Django 5.2.17 on 2026-08-16 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CargoMesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=50, unique=True, verbose_name="Cargo"),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(verbose_name="Ordem de precedência"),
                ),
            ],
            options={
                "verbose_name": "Cargo da Mesa",
                "verbose_name_plural": "Cargos da Mesa",
                "ordering": ("ordem",),
            },
        ),
        migrations.CreateModel(
            name="Comissao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, unique=True, verbose_name="Nome"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("P", "Permanente"),
                            ("T", "Temporária/Especial"),
                            ("C", "Comissão Parlamentar de Inquérito"),
                            ("R", "Comissão Processante"),
                        ],
                        default="P",
                        max_length=1,
                        verbose_name="Tipo",
                    ),
                ),
                ("finalidade", models.TextField(blank=True, verbose_name="Finalidade")),
                (
                    "data_criacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "data_extincao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de extinção"
                    ),
                ),
                ("ativa", models.BooleanField(default=True, verbose_name="Ativa")),
            ],
            options={
                "verbose_name": "Comissão",
                "verbose_name_plural": "Comissões",
                "ordering": ("nome",),
            },
        ),
        migrations.CreateModel(
            name="Partido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sigla",
                    models.CharField(max_length=20, unique=True, verbose_name="Sigla"),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Partido",
                "verbose_name_plural": "Partidos",
                "ordering": ("sigla",),
            },
        ),
        migrations.CreateModel(
            name="Vereador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_civil",
                    models.CharField(max_length=150, verbose_name="Nome civil"),
                ),
                (
                    "nome_parlamentar",
                    models.CharField(max_length=100, verbose_name="Nome parlamentar"),
                ),
                (
                    "foto",
                    models.FileField(
                        blank=True, upload_to="vereadores/", verbose_name="Foto"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Telefone"
                    ),
                ),
                ("biografia", models.TextField(blank=True, verbose_name="Biografia")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "partido",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parlamentares.partido",
                        verbose_name="Partido atual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vereador",
                "verbose_name_plural": "Vereadores",
                "ordering": ("nome_parlamentar",),
            },
        ),
        migrations.CreateModel(
            name="MembroComissao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cargo",
                    models.CharField(
                        choices=[
                            ("P", "Presidente"),
                            ("V", "Vice-Presidente"),
                            ("M", "Membro"),
                            ("S", "Suplente"),
                        ],
                        default="M",
                        max_length=1,
                        verbose_name="Cargo",
                    ),
                ),
                (
                    "periodo",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: 2025/2026",
                        max_length=20,
                        verbose_name="Período",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateField(blank=True, null=True, verbose_name="Início"),
                ),
                (
                    "data_fim",
                    models.DateField(blank=True, null=True, verbose_name="Fim"),
                ),
                (
                    "comissao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membros",
                        to="parlamentares.comissao",
                        verbose_name="Comissão",
                    ),
                ),
                (
                    "vereador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comissoes",
                        to="parlamentares.vereador",
                        verbose_name="Vereador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membro de Comissão",
                "verbose_name_plural": "Membros de Comissões",
                "ordering": ("comissao", "cargo"),
            },
        ),
        migrations.CreateModel(
            name="Mandato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condicao",
                    models.CharField(
                        choices=[("T", "Titular"), ("S", "Suplente em exercício")],
                        default="T",
                        max_length=1,
                        verbose_name="Condição",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Início do exercício")),
                (
                    "data_fim",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fim do exercício"
                    ),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="Observação")),
                (
                    "legislatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mandatos",
                        to="core.legislatura",
                        verbose_name="Legislatura",
                    ),
                ),
                (
                    "vereador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mandatos",
                        to="parlamentares.vereador",
                        verbose_name="Vereador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mandato",
                "verbose_name_plural": "Mandatos",
                "ordering": ("legislatura", "vereador__nome_parlamentar"),
            },
        ),
        migrations.CreateModel(
            name="ComposicaoMesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Início")),
                (
                    "data_fim",
                    models.DateField(blank=True, null=True, verbose_name="Fim"),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parlamentares.cargomesa",
                        verbose_name="Cargo",
                    ),
                ),
                (
                    "legislatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="composicoes_mesa",
                        to="core.legislatura",
                        verbose_name="Legislatura",
                    ),
                ),
                (
                    "vereador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cargos_mesa",
                        to="parlamentares.vereador",
                        verbose_name="Vereador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Composição da Mesa",
                "verbose_name_plural": "Composições da Mesa",
                "ordering": ("-data_inicio", "cargo__ordem"),
            },
        ),
    ]
